#ifndef MINISNN_WORLDS_KERNEL_EVENT_H
#define MINISNN_WORLDS_KERNEL_EVENT_H

#include <stdbool.h>
#include <stddef.h>

#include "minisnn_worlds_kernel_types.h"
#include "minisnn_worlds_kernel_space.h"
#include "minisnn_worlds_kernel_occupancy.h"
#include "minisnn_worlds_kernel_spatial_link.h"

typedef enum
{
    MINISNN_WORLDS_KERNEL_EVENT_ENTITY_CREATED = 1,
    MINISNN_WORLDS_KERNEL_EVENT_ENTITY_DESTROYED = 2,
    MINISNN_WORLDS_KERNEL_EVENT_COMMAND_REJECTED = 3,
    MINISNN_WORLDS_KERNEL_EVENT_ENTITY_PLACED = 4,
    MINISNN_WORLDS_KERNEL_EVENT_ENTITY_REMOVED_FROM_SPACE = 5,
    MINISNN_WORLDS_KERNEL_EVENT_OCCUPANCY_SET = 6,
    MINISNN_WORLDS_KERNEL_EVENT_OCCUPANCY_CLEARED = 7,
    MINISNN_WORLDS_KERNEL_EVENT_ENTITY_MOVED = 8,
    MINISNN_WORLDS_KERNEL_EVENT_SPATIAL_LINK_CREATED = 9,
    MINISNN_WORLDS_KERNEL_EVENT_SPATIAL_LINK_REMOVED = 10
} MiniSNNWorldsKernelEventType;

typedef enum
{
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_NONE = 0,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_ISSUER_NOT_ALIVE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_NOT_ALIVE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_INVALID_COMMAND,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_ALREADY_PLACED,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_NOT_PLACED,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_POSITION_OUT_OF_BOUNDS,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_INVALID_ORIENTATION,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_INVALID_OCCUPANCY,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_HAS_NO_OCCUPANCY,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_OCCUPANCY_OUT_OF_BOUNDS,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_OCCUPANCY_CONFLICT,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_DESTINATION_OVERFLOW,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_PARENT_NOT_ALIVE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_CHILD_NOT_ALIVE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_SELF,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_PARENT_NOT_PLACED,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_CHILD_NOT_PLACED,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_DUPLICATE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_CHILD_HAS_PARENT,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_CYCLE,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_OFFSET_OVERFLOW,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_SPATIAL_LINK_NOT_FOUND,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_HAS_SPATIAL_PARENT,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_HAS_SPATIAL_CHILDREN,
    MINISNN_WORLDS_KERNEL_COMMAND_REJECTION_TARGET_HAS_SPATIAL_LINKS
} MiniSNNWorldsKernelCommandRejection;

typedef struct
{
    MiniSNNWorldsKernelEventId event_id;
    MiniSNNWorldsTick tick;
    MiniSNNWorldsKernelEventType type;
    MiniSNNWorldsKernelCommandId command_id;
    MiniSNNWorldsKernelEntityId issuer;
    MiniSNNWorldsKernelEntityId subject;
    MiniSNNWorldsKernelEntityId related_entity;
    MiniSNNWorldsKernelCommandRejection rejection;
    bool has_previous_transform;
    MiniSNNWorldsKernelTransform previous_transform;
    bool has_transform;
    MiniSNNWorldsKernelTransform transform;
    bool has_displacement;
    MiniSNNWorldsKernelPosition displacement;
    bool has_occupancy;
    MiniSNNWorldsKernelOccupancy occupancy;
    bool has_spatial_link;
    MiniSNNWorldsKernelSpatialLink spatial_link;
    MiniSNNWorldsKernelEntityId affected_entity;
} MiniSNNWorldsKernelEvent;

size_t minisnn_worlds_kernel_last_tick_event_count(
    const MiniSNNWorldsKernel *kernel);

MiniSNNWorldsKernelError minisnn_worlds_kernel_last_tick_event_at(
    const MiniSNNWorldsKernel *kernel,
    size_t canonical_index,
    MiniSNNWorldsKernelEvent *out_event);

#endif
