#ifndef MINISNN_WORLDS_KERNEL_TYPES_H
#define MINISNN_WORLDS_KERNEL_TYPES_H

#include <stdint.h>

typedef uint64_t MiniSNNWorldsTick;

#define MINISNN_WORLDS_TICK_INITIAL UINT64_C(0)

typedef enum
{
    MINISNN_WORLDS_KERNEL_ERROR_NONE = 0,
    MINISNN_WORLDS_KERNEL_ERROR_NULL_ARGUMENT,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_CONFIG,
    MINISNN_WORLDS_KERNEL_ERROR_ALLOCATION,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_STATE,
    MINISNN_WORLDS_KERNEL_ERROR_TICK_OVERFLOW,
    MINISNN_WORLDS_KERNEL_ERROR_INTERNAL
} MiniSNNWorldsKernelError;

typedef enum
{
    MINISNN_WORLDS_KERNEL_STATE_READY = 0,
    MINISNN_WORLDS_KERNEL_STATE_STEPPING,
    MINISNN_WORLDS_KERNEL_STATE_FAULTED
} MiniSNNWorldsKernelState;

typedef struct MiniSNNWorldsKernel MiniSNNWorldsKernel;

#endif
