#ifndef MINISNN_WORLDS_KERNEL_TYPES_H
#define MINISNN_WORLDS_KERNEL_TYPES_H

#include <stdint.h>

typedef uint64_t MiniSNNWorldsTick;

#define MINISNN_WORLDS_TICK_INITIAL UINT64_C(0)

typedef struct
{
    uint64_t value;
} MiniSNNWorldsKernelEntityId;

typedef struct
{
    uint64_t value;
} MiniSNNWorldsKernelCommandId;

typedef struct
{
    uint64_t value;
} MiniSNNWorldsKernelEventId;

typedef enum
{
    MINISNN_WORLDS_KERNEL_ERROR_NONE = 0,
    MINISNN_WORLDS_KERNEL_ERROR_NULL_ARGUMENT,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_CONFIG,
    MINISNN_WORLDS_KERNEL_ERROR_ALLOCATION,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_STATE,
    MINISNN_WORLDS_KERNEL_ERROR_TICK_OVERFLOW,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_ENTITY_ID,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_COMMAND,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_TICK,
    MINISNN_WORLDS_KERNEL_ERROR_INDEX_OUT_OF_RANGE,
    MINISNN_WORLDS_KERNEL_ERROR_IDENTIFIER_OVERFLOW,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_RANDOM_STREAM_KEY,
    MINISNN_WORLDS_KERNEL_ERROR_INVALID_BOUND,
    MINISNN_WORLDS_KERNEL_ERROR_INTERNAL
} MiniSNNWorldsKernelError;

typedef enum
{
    MINISNN_WORLDS_KERNEL_STATE_READY = 0,
    MINISNN_WORLDS_KERNEL_STATE_STEPPING,
    MINISNN_WORLDS_KERNEL_STATE_FAULTED
} MiniSNNWorldsKernelState;

typedef struct MiniSNNWorldsKernel MiniSNNWorldsKernel;

#endif
